#!/bin/bash
#Stefan Koch, 2019

host=$(grep SERVER_HOST config.yml | awk '{print $2}')
port=$(grep SSH_PORT    config.yml | awk '{print $2}')

echo "[hostgroup]" > hosts
echo "host_base ansible_host=$host ansible_port=22" >> hosts
echo "host_snew ansible_host=$host ansible_port=$port" >> hosts

